name: Run Appium Tests on Android Emulator

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17  # <-- FIXED JAVA VERSION
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Run emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: "-no-window -no-audio"
          script: |
            adb devices
            adb wait-for-device
            echo "Running Appium Tests..."
            mvn test || echo "Test failed"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/
