name: Android Appium Test

on:
  workflow_dispatch:

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Appium and dependencies
      run: |
        npm install -g appium
        appium -v

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Create and start emulator
      run: |
        echo "y" | sdkmanager "system-images;android-30;google_apis;x86"
        echo "no" | avdmanager create avd -n Akil3 -k "system-images;android-30;google_apis;x86" --device "pixel"
        $ANDROID_HOME/emulator/emulator -avd Akil3 -no-audio -no-window -gpu swiftshader_indirect &

    - name: Wait for emulator to boot
      run: |
        adb wait-for-device
        adb shell getprop sys.boot_completed
        until adb shell getprop sys.boot_completed | grep -m 1 '1'; do
          sleep 5
        done
        adb shell input keyevent 82

    - name: Start Appium server
      run: |
        nohup appium --base-path /wd/hub &

    - name: Run Appium tests
      run: mvn test
