name: Appium Android Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from your repo
    - name: Check out code
      uses: actions/checkout@v2

    # Step 2: Set up Java (required for Appium and your tests)
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Use the version you need, like 11 or 8

    # Step 3: Set up Android SDK and install required dependencies
    - name: Set up Android SDK
      run: |
        sudo apt update
        sudo apt install -y wget unzip lib32stdc++6 lib32z1
        wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        unzip commandlinetools-linux-6858069_latest.zip -d $HOME/android-sdk
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT --update
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86_64"

    # Step 4: Install Appium and other necessary dependencies
    - name: Install Appium and dependencies
      run: |
        npm install -g appium
        npm install -g appium-doctor
        appium-doctor --android

    # Step 5: Create and Start Android Emulator (Akil3)
    - name: Create and Start Android Emulator (Akil3)
      run: |
        echo "Creating and Starting Android Emulator Akil3..."
        # Create the emulator (if it doesn't already exist)
        echo "no" | avdmanager create avd -n Akil3 -k "system-images;android-30;google_apis;x86_64" --force
        # Start the emulator
        emulator -avd Akil3 -no-window -gpu off &
        adb wait-for-device
        adb shell input keyevent 82 &  # Unlock the device if needed

    # Step 6: Run your Appium tests
    - name: Run Appium tests
      run: |
        # Assuming you are using Maven/Gradle/Direct Java Execution
        # Run the test using Maven or Gradle (adjust as needed)
        mvn test  # or ./gradlew test
