name: Run Appium Tests on Android Emulator

on:
  workflow_dispatch:

jobs:
  appium-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Node.js for Appium
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium and UIAutomator2 driver
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Start Android Emulator and run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_3
          emulator-options: "-no-window -no-audio -no-boot-anim -accel off"
          disable-animations: true
          script: |
            echo "Starting Appium server"
            nohup appium --log appium.log > /dev/null 2>&1 &
            sleep 15
            echo "Checking Appium is up..."
            curl http://localhost:4723/wd/hub/status || exit 1
            echo "Running Maven tests..."
            mvn test
