name: Android Appium Test

on:
  workflow_dispatch:

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Appium and dependencies
      run: |
        npm install -g appium
        appium -v

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86
        profile: pixel
        emulator-options: -no-window -no-audio
        script: |
           adb devices
           adb shell input keyevent 82
           mvn test

    - name: Wait for emulator to boot
      run: |
        adb wait-for-device
        adb shell getprop sys.boot_completed
        until adb shell getprop sys.boot_completed | grep -m 1 '1'; do
          sleep 5
        done
        adb shell input keyevent 82

    - name: Start Appium server
      run: |
        nohup appium --base-path /wd/hub &

    - name: Run Appium tests
      run: mvn test
