name: Run Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Run emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: arm64-v8a
          profile: Nexus 6
          emulator-options: -no-window -no-audio -no-snapshot
          disable-animations: true
          script: |
            timeout=0
            while [[ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" && $timeout -lt 300 ]]; do
              sleep 5
              timeout=$((timeout + 5))
              echo "Waiting for emulator to boot... ($timeout seconds)"
            done
            if [ "$timeout" -ge 300 ]; then
              echo "Emulator did not boot in time"
              exit 1
            fi

            echo "Emulator booted. Running tests..."
            mvn test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/
