name: Manual Run - Appium Android Tests

on:
  workflow_dispatch:  # This allows manual run from GitHub UI

jobs:
  run-tests:
    name: Run Appium Tests on Emulator
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Android Emulator and Run Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: pixel_4
        emulator-options: "-no-window -no-audio"
        disable-animations: true
        script: |
          echo "Installing Appium..."
          npm install -g appium
          appium --log-level info &
          echo "Waiting for Appium to start..."
          sleep 15
          echo "Running TestNG tests using Maven..."
          mvn test

    - name: Upload TestNG Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testng-report
        path: test-output
