name: Appium Android Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from your repo
    - name: Check out code
      uses: actions/checkout@v2

    # ✅ FIXED: Proper indentation for setting up Java
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Step 3: Set up Android SDK and install required dependencies
    - name: Set up Android SDK
      run: |
        sudo apt update
        sudo apt install -y wget unzip lib32stdc++6 lib32z1
        wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        unzip commandlinetools-linux-6858069_latest.zip -d $HOME/android-sdk
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT --update
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86_64"

    # Step 4: Install Appium and other necessary dependencies
    - name: Install Appium and dependencies
      run: |
        npm install -g appium
        npm install -g appium-doctor
