name: Appium Android Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: $HOME/android-sdk
      AVD_NAME: Akil3

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Android SDK Command Line Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip lib32stdc++6 lib32z1 libpulse0
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip tools.zip -d $ANDROID_HOME/cmdline-tools/tmp
        mv $ANDROID_HOME/cmdline-tools/tmp/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

    - name: Set up Android paths
      run: |
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH

    - name: Accept SDK Licenses and Install Packages
      run: |
        sdkmanager --sdk_root=${ANDROID_HOME} --licenses
        sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" "emulator" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86_64"

    - name: Install Appium
      run: |
        npm install -g appium
        npm install -g appium-doctor
        appium-doctor --android

    - name: Create and Start Emulator
      run: |
        echo "no" | avdmanager create avd -n $AVD_NAME -k "system-images;android-30;google_apis;x86_64" --device "pixel" --force
        emulator -avd $AVD_NAME -no-audio -no-window -gpu off &
        adb wait-for-device
        adb shell input keyevent 82

    - name: Start Appium Server
      run: |
        appium --base-path /wd/hub --log-level info &
        sleep 10

    - name: Run Appium Tests
      run: mvn test
