name: Emulator Test

on:
  workflow_dispatch:

jobs:
  emulator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: pixel
          emulator-options: "-no-window -no-audio"
          disable-animations: true
          script: |
            echo "✅ Emulator booted!"
            adb devices
