name: Android Appium Test

on:
  workflow_dispatch:

jobs:
  appium-tests:
    runs-on: macos-latest  # Use macOS runner to avoid emulator boot issues

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium and dependencies
        run: |
          npm install -g appium
          appium -v

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Run Appium Tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86
          profile: pixel
          emulator-options: -no-window -no-audio -no-snapshot
          emulator-boot-timeout: 600  # wait up to 10 minutes
          script: |
            echo "Starting Appium..."
            nohup appium --base-path /wd/hub > appium.log 2>&1 &
            sleep 20  # Give Appium time to start
            adb shell input keyevent 82  # Unlock emulator
            mvn test
