name: Run Appium Tests on Android Emulator

on:
  workflow_dispatch:

jobs:
  appium-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Node.js for Appium
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium and driver
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Start emulator and run Appium tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_3
          emulator-options: "-no-window -no-audio -no-boot-anim -accel off"
          disable-animations: true
          script: |
            echo "Starting Appium server..."
            nohup appium --log appium.log > /dev/null 2>&1 &

            echo "Waiting for Appium to be ready..."
            for i in {1..15}; do
              if curl -s http://localhost:4723/wd/hub/status | grep -q "Appium"; then
                echo "Appium is ready!"
                break
              fi
              echo "Waiting... ($i)"
              sleep 2
            done

            echo "Running Appium tests via Maven..."
            mvn test || (echo "Tests failed! Dumping logs:" && cat appium.log && exit 1)

      - name: Upload Appium log (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-log
          path: appium.log
