name: Run Appium Tests on Android Emulator

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Install Android SDK tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip lib32stdc++6 lib32z1 libqt5widgets5 libqt5gui5 libqt5core5a

      - name: Download Android command line tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          rm cmdline-tools.zip

      - name: Update SDK and install emulator + system images
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

      - name: Create and start emulator
        run: |
          echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n test_emulator -k "system-images;android-30;google_apis;x86_64" --force
          $ANDROID_SDK_ROOT/emulator/emulator -avd test_emulator -no-window -no-audio -no-boot-anim &
          echo "Waiting for emulator to boot..."
          adb wait-for-device
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>&1 | tr -d '\r')
            echo "Boot completed: $boot_completed"
            sleep 5
          done
          adb shell input keyevent 82

      - name: Verify device is connected
        run: adb devices

      - name: Run your Appium tests
        run: |
          # Replace below with your actual test command
          echo "Running Appium tests..."
          # e.g., mvn test or npm test or appium --some-command
          # For example:
          # mvn clean test
