name: Run Appium Tests on Android Emulator

on:
  workflow_dispatch:

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip lib32stdc++6 lib32z1 qemu-kvm

      - name: Set Android SDK environment
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/emulator" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Download Android command line tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          rm cmdline-tools.zip

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install SDK packages
        run: sdkmanager "platform-tools" "platforms;android-33" "system-images;android-33;google_apis;x86_64" "emulator"

      - name: Create AVD named Akil3
        run: |
          echo "no" | avdmanager create avd -n Akil3 -k "system-images;android-33;google_apis;x86_64" --force

      - name: Start Android Emulator
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/platform-tools:$PATH

          echo "Available AVDs:"
          $ANDROID_SDK_ROOT/emulator/emulator -list-avds

          echo "Starting emulator..."
          nohup $ANDROID_SDK_ROOT/emulator/emulator -avd Akil3 \
            -no-snapshot \
            -no-audio \
            -no-boot-anim \
            -gpu swiftshader_indirect \
            -no-window \
            -accel off > emulator.log 2>&1 &

          echo "Waiting for emulator to boot..."
          bootanim=""
          until [[ "$bootanim" == "stopped" ]]; do
            bootanim=$(adb -e shell getprop init.svc.bootanim 2>/dev/null | tr -d '\r')
            echo "  → boot status: $bootanim"
            sleep 5
          done

          adb shell input keyevent 82

      - name: Run Appium tests
        run: mvn test

      - name: Stop emulator
        if: always()
        run: |
          export PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/emulator:$PATH
          adb -s emulator-5554 emu kill || echo "Emulator already killed"
